#!/usr/bin/env bash

TEMPLATES=$(dirname $(dirname "${BASH_SOURCE[0]}"))/templates

set -e

REPO_ROOT_PATH=$(git rev-parse --show-toplevel 2>/dev/null)
if [ -n "$REPO_ROOT_PATH" ]; then
    cd $REPO_ROOT_PATH
fi

mkdir -p deploy

if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    git submodule add --force https://github.com/Deimvis/DTOOLS.git deploy/_DTOOLS
else
    git clone https://github.com/Deimvis/DTOOLS.git deploy/_DTOOLS
fi

cp $TEMPLATES/cmd deploy/cmd
chmod +x deploy/cmd
echo '{ "example_key": "example_value" }' | jq > deploy/hkv.json

mkdir -p deploy/local/example/cmd
mkdir -p deploy/docker/example/cmd
mkdir -p deploy/vm/example/cmd

cp $TEMPLATES/vm_deploy deploy/vm/example/cmd/deploy
chmod +x deploy/vm/example/cmd/deploy
cp $TEMPLATES/vm_hkv.json deploy/vm/example/cmd/hkv.json

